DAOS-6803 ofi: Update to ofi v1.12.0rc1
daos-stack/libfabric pull request #34
Opened 2021-02-16 18:02 UTC by frostedcmos

- Update to v1.12.0rc1

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

2021-02-16 21:45 UTC, brianjmurrell requested changes
GH review won't let me say so in the PR since it was not a line modified by you, but you also need to update https://github.com/daos-stack/libfabric/blob/1c5b13ddf7c356434f2fb45928f2b934dfff9747/libfabric.spec#L16 to
```
Source: https://github.com/ofiwg/%{name}/archive/v%{dl_version}.tar.gz
```

2021-02-16 21:45 UTC, brianjmurrell commented on libfabric.spec
> +%global dl_version 1.12.0rc1
We're starting to gravitate towards some standards that allow us to easily switch between _pre_ and _GA_ releases of packages without having to change lots of things all over the spec file.  First we start with defining the components of the version and build the `%dl_version` from it:

```suggestion
%global major 1
%global minor 12
%global bugrelease 0
%global prerelease rc1
%global dl_version  %{major}.%{minor}.%{bugrelease}%{?prerelease:%{prerelease}}
```

2021-02-16 21:45 UTC, brianjmurrell commented on libfabric.spec
> +Version: 1.12.0~rc1
Next we define the version from the components:
```suggestion
Version: 1.12.0~rc1
Version: %{major}.%{minor}.%{bugrelease}%{?prerelease:~%{prerelease}}
```

2021-02-16 21:45 UTC, brianjmurrell commented on libfabric.spec
> +%autosetup -n libfabric-%dl_version
Then make a portable `%{autosetup}` that doesn't need changing every time:
```suggestion
%autosetup -p1 -n libfabric-%dl_version
```

2021-02-17 13:23 UTC, brianjmurrell requested changes

2021-02-17 13:23 UTC, brianjmurrell commented on packaging/Jenkinsfile
> +#!/usr/bin/groovy
This file doesn't need to be added.  Did you use `<path_to_local_packaging_dir>/install` to update the packaging?  IIRC, that only copied the needed files for a `packaging/` update.

2021-02-17 13:23 UTC, brianjmurrell commented on packaging/Makefile
> +endif
I think we can get rid of these lines now.  We soooo don't support those distros any more.

2021-02-17 13:23 UTC, brianjmurrell commented on packaging/Makefile
> +LEAP_15_REPOS := $(OSUSE_HPC_REPO)/openSUSE_Leap_15.1/
This should probably be updated:
```suggestion
LEAP_15_REPOS := $(OSUSE_HPC_REPO)/openSUSE_Leap_15.2/
```

In fact it probably should be _determined automatically_:

```suggestion
LEAP_15_REPOS := $(OSUSE_HPC_REPO)/openSUSE_Leap_$(lsb_release -s -r)/
```

should work.

2021-02-17 13:23 UTC, brianjmurrell commented on packaging/README.md
> +# Common Packaging files and scripts
This file doesn't need to be added.

2021-02-17 13:23 UTC, brianjmurrell commented on packaging/install
> +#!/bin/bash
Nor this one.

2021-02-17 16:42 UTC, frostedcmos commented
Daos testing with new OFI passed in https://github.com/daos-stack/daos/pull/4666
Two failures there are known issues also happening on latest master: https://build.hpdd.intel.com/job/daos-stack/job/daos/job/master/3872/

2021-02-17 17:37 UTC, brianjmurrell approved these changes

2021-02-17 17:44 UTC, brianjmurrell commented
> Daos testing with new OFI passed in [daos-stack/daos#4666](https://github.com/daos-stack/daos/pull/4666)

Great.  Do you think we need to test this PR with current master to ensure that if we land it, it's compatible with everything that is in-flight or do you have confidence that there is nothing in this update that would break compatibility with current master?

2021-02-17 17:49 UTC, frostedcmos commented
> > Daos testing with new OFI passed in [daos-stack/daos#4666](https://github.com/daos-stack/daos/pull/4666)
> 
> Great. Do you think we need to test this PR with current master to ensure that if we land it, it's compatible with everything that is in-flight or do you have confidence that there is nothing in this update that would break compatibility with current master?

I am not aware of anything that would break compatibility with this update. All OFI apis that mercury uses are backwards compatible and thats the only component that uses OFI directly.

2021-02-17 22:16 UTC, jolivier23 approved these changes

2021-02-19 21:03 UTC, merged