CART-954 ofi: Update ofi to 1.12.0
daos-stack/libfabric pull request #36
Opened 2021-03-10 20:43 UTC by frostedcmos

- Update to OFI 1.12.0
- Disable gdrcopy/gdrapi linkage as this library is not required
for any of our operations

Signed-off-by: Alexander Oganezov <alexander.a.oganezov@intel.com>

2021-03-10 21:25 UTC, frostedcmos commented
Corresponding DAOS update https://github.com/daos-stack/libfabric/pull/36

2021-03-10 22:32 UTC, brianjmurrell requested changes
> Corresponding DAOS update [daos-stack/daos#4950](https://github.com/daos-stack/daos/pull/4950)

This is this PR.

2021-03-10 22:32 UTC, brianjmurrell commented on debian/changelog
> + -- Alexander Oganezov <alexander.a.oganezov@intel.com>  Tue, 16 Feb 2021 13:54:52 -0400
Update the datestamp here?

2021-03-11 16:04 UTC, jgmoore-or approved these changes

2021-03-12 15:23 UTC, jolivier23 approved these changes
Just getting it out of my inbox as I assume we won't land this until the DAOS PR completes

2021-03-28 16:51 UTC, merged