DAOS-9883 libfabric: Apply patch for TCP provider
daos-stack/libfabric pull request #53
Opened 2022-02-28 16:59 UTC by dmiter

Commit 45dce66 incorrectly negated a check that is used to signal
any threads waiting on a cq to wake up. Without this signal,
applications can hang, as reported in issue 7443. The situation is
as follows:

A thread waits for completions on the CQ. At the time that the thread
blocks, the socket has no outgoing transfers, so the thread calls
poll looking for a POLLIN event.

Another thread tries to send a large transfer. A portion of the data
is accepted by the socket. The rest of the transfer is queued on the ep.
That thread returns. Additional messages may be posted to the ep, but
since there's already an active transfer, those messages simply get
queued on the tx_queue.

Note that the thread that was blocked on the CQ is still blocked waiting
for a POLLIN event. However, it should be waiting for POLLOUT | POLLIN.
The signal in this case isn't trying to drive progress, like the original
commit suggests, but is needed to update the poll call.

Reverse the check, so that blocked threads wake up and can update their
poll event status.

Signed-off-by: Sean Hefty sean.hefty@intel.com

2022-03-01 14:28 UTC, dmiter commented
@brianjmurrell it looks the CHROOT_NAME=rocky+epel-8-x86_64 and CHROOT_NAME=centos+epel-7-x86_64 are not expected in build scripts. Can you help me fix this?

2022-03-02 18:55 UTC, brianjmurrell requested changes
You have not updated the `packaging/` subdir in this PR.

Every PR **MUST** include any updates from [packaging@master](https://github.com/daos-stack/packaging/tree/master) that are not in the current `packaging/` subdir.  This is most easiest done by checking out the above and then from the directory your libfabric PR is in running `<path-to-packaging-master-checkout>/install`.  So for example:

```
workdir/libfabric$ cd ..
workdir$ git clone git@github.com:daos-stack/packaging.git
workdir$ cd libfabric
workdir/libfabric$ ../install
```

2022-03-02 18:55 UTC, brianjmurrell commented on .github/CODEOWNERS
> +* @release-engineering
This syntax is invalid.  The correct syntax/content was provided in the error message in your first PR commit at https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Flibfabric/detail/PR-53/1/pipeline

```suggestion
# Have Release Engineering added as a reviewer to any packaging PR
* @daos-stack/build-and-release-watchers
```

2022-03-02 20:13 UTC, brianjmurrell submitted a review, later dismissed

2022-04-04 14:06 UTC, brianjmurrell commented
@dmiter

> - dmiter requested a review from brianjmurrell last month
> ...
> - dmiter force-pushed the DAOS-9883 branch from a759437 to 08e7c22 Compare4 hours ago
> ...
> - dmiter force-pushed the DAOS-9883 branch from 08e7c22 to 7a51715 Compare4 hours ago

Please remember that we do not allow force-pushes once you have started requesting reviews.

2022-04-04 16:16 UTC, frostedcmos approved these changes

2022-04-05 16:09 UTC, dmiter commented
Can we land this? All DAOS tests passed with this libfabric. The modification of DAOS is prepared: https://github.com/daos-stack/daos/pull/8613

2022-04-05 23:29 UTC, jolivier23 approved these changes

2022-04-06 02:35 UTC, merged

2022-04-06 02:36 UTC, brianjmurrell commented
> Can we land this? All DAOS tests passed with this libfabric. The modification of DAOS is prepared: [daos-stack/daos#8613](https://github.com/daos-stack/daos/pull/8613)

Landed.  Just so you know, you can/should add @daos-stack/release-engineering when you are ready for landing.  This prevents unintentional premature landings that could break things.